name: Python CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with Black
        run: |
          black . --check -l 120

      - name: Test with unittest
        run: |
          if [ -d tests ]; then 
            pytest tests; 
          fi

      - name: Check types with mypy
        run: |
          if [ -f *.py ]; then
            mypy . --ignore-missing-imports;
          fi